[package]
name = "dmclc5"
version = "0.3.2"
authors = ["heipiao233"]
edition = "2024"
description = "A minecraft launching library"
documentation = "https://docs.rs/dmclc5"
license = "GPL-3.0"
repository = "https://github.com/heipiao233/dmclc5"

[dependencies]
anyhow = "1"
async-fetcher = "0.12.0"
base64 = "0.22"
digest-io = "0.1.0"
either = "1.16.0"
enum_dispatch = "0.3.13"
form_urlencoded = { version = "1", optional = true }
fs_extra = { version = "1", optional = true }
futures = { version = "0.3", optional = true }
futures-util = { version = "0.3", features = ["io"] }
hex = "0.4.3"
join-string = "0.3.0"
keyring = "4.1.2"
markdown-it = { version = "0.6", optional = true }
md5 = "0.8"
murmur2 = { version = "0.1", optional = true }
oauth2 = { version = "5.0.0", optional = true }
open = { version = "5", optional = true }
osstrtools-fix = "0.2.3"
reqwest = { version = "0.12", features = ["blocking", "json", "stream"] }
rust-i18n = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = { version = "0.1", optional = true }
serde_str = "0.1.0"
sha1 = "0.11"
sha2 = "0.11"
tempfile = { version = "3", optional = true }
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "process", "io-std", "rt-multi-thread"] }
tokio-util = { version = "0.7", features = ["compat"] }
toml = { version = "1.0", optional = true }
uuid = { version = "1", features = ["serde"] }
versions = { version = "7", features = ["serde"], optional = true }
xmltree = { version = "0.12", optional = true }
zip = "8"

[features]
components_installation = ["dep:form_urlencoded", "dep:fs_extra", "dep:tempfile", "dep:xmltree"]
mod_loaders = ["components_installation", "dep:toml", "dep:versions"]
content_services = ["dep:futures", "dep:markdown-it", "dep:murmur2", "dep:serde_repr"]
msa_auth = ["dep:open", "dep:oauth2"]

[[example]]
name = "basic_minecraft"
path = "examples/minecraft.rs"
required-features = ["msa_auth"]

[[example]]
name = "contents"
path = "examples/contents.rs"
required-features = ["content_services"]

[[example]]
name = "mod_loaders"
path = "examples/mod_loader.rs"
required-features = ["mod_loaders"]
